apiVersion: v1
kind: Pod
metadata:
  name: multi-pod
  namespace: dev
  labels:
    app: dev
spec:
  containers:
    - name: web
      image: nginx
      ports:
        - name: web
          containerPort: 80
          protocol: TCP
    - name: redis
      image: redis
      ports:
        - name: redis
          containerPort: 6379

