apiVersion: v1

kind: Pod

metadata:
  name: test-pod
  labels:
    app: test
  namespace: dev

spec:
  containers:
    - name: test-container
      image: nginx
    - name: test-container-2
      image: redis

