apiVersion: v1
kind: Pod
metadata:
  name: static-web
  namespace: dev
  labels:
    app: dev
spec:
  containers:
    - name: web
      image: nginx
      ports:
        - name: web
          containerPort: 80
          protocol: TCP
